import { StyleSheet } from "react-native";
import { COLORS } from "../constants/accountability";

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: COLORS.bg },
  scrollBg: { flex: 1, backgroundColor: COLORS.bg },

  centerWrap: { padding: 18, flexGrow: 1, justifyContent: "center" },
  welcomeCard: {
    backgroundColor: COLORS.card,
    borderRadius: 24,
    padding: 20,
    borderWidth: 1,
    borderColor: COLORS.borderSoft,
    shadowColor: "#231F5B",
    shadowOpacity: 0.06,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 2,
  },
  heartCircle: {
    width: 78,
    height: 78,
    borderRadius: 39,
    alignSelf: "center",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: COLORS.primary,
  },
  heart: {
    fontSize: 30,
    color: "#FFFFFF",
    marginTop: 1,
    fontWeight: "900",
  },
  welcomeTitle: {
    marginTop: 16,
    fontSize: 24,
    fontWeight: "800",
    color: COLORS.text,
    textAlign: "center",
  },
  welcomeSub: {
    marginTop: 8,
    fontSize: 13,
    lineHeight: 18,
    color: COLORS.subtext,
    textAlign: "center",
  },
  promptTitle: {
    marginTop: 16,
    fontSize: 18,
    fontWeight: "800",
    color: COLORS.pinkText,
    textAlign: "center",
  },
  textArea: {
    marginTop: 14,
    minHeight: 120,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: COLORS.border,
    padding: 12,
    fontSize: 13,
    color: COLORS.text,
    backgroundColor: COLORS.white,
  },
  primaryBtn: {
    marginTop: 16,
    height: 52,
    borderRadius: 16,
    backgroundColor: COLORS.primary,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 10,
  },
  primaryBtnText: { color: "#FFFFFF", fontSize: 15, fontWeight: "800" },
  primaryBtnArrow: {
    color: "#FFFFFF",
    fontSize: 18,
    fontWeight: "800",
    marginTop: -1,
  },
  skipWrap: { marginTop: 14, alignItems: "center" },
  skipText: { color: COLORS.subtext, fontSize: 13, fontWeight: "600" },

  pagePad: { padding: 16, paddingBottom: 30 },
  pageTitle: { fontSize: 26, fontWeight: "900", color: COLORS.primary },
  pageSub: { marginTop: 4, fontSize: 13, color: COLORS.subtext },

  tabRow: {
    marginTop: 18,
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "flex-end",
  },
  tabBtn: {
    alignItems: "center",
    paddingVertical: 8,
    paddingHorizontal: 14,
    minWidth: 120,
  },
  tabIcon: { fontSize: 18, color: "#A3A0B8" },
  tabIconActive: { color: COLORS.primary },
  tabLabel: {
    marginTop: 6,
    fontSize: 12,
    fontWeight: "700",
    color: "#A3A0B8",
  },
  tabLabelActive: { color: COLORS.primary },
  simpleUnderline: {
    marginTop: 8,
    height: 3,
    width: 68,
    borderRadius: 999,
    backgroundColor: COLORS.pinkText,
  },

  card: {
    backgroundColor: COLORS.card,
    borderRadius: 20,
    padding: 14,
    borderWidth: 1,
    borderColor: COLORS.border,
    shadowColor: "#231F5B",
    shadowOpacity: 0.05,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 2,
  },
  cardTitle: { fontSize: 14, fontWeight: "900", color: COLORS.text },
  cardSub: { marginTop: 4, fontSize: 12, color: COLORS.subtext },
  sectionTitle: { fontSize: 14, fontWeight: "900", color: COLORS.text },
  sectionMiniTitle: {
    fontSize: 12,
    fontWeight: "900",
    color: COLORS.subtext,
    marginBottom: 4,
  },
  formLabel: {
    marginBottom: 6,
    fontSize: 12,
    fontWeight: "800",
    color: COLORS.text,
  },

  addRow: {
    marginTop: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  input: {
    flex: 1,
    minHeight: 44,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: COLORS.border,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 13,
    color: COLORS.text,
    backgroundColor: COLORS.white,
  },

  addBtnPurple: {
    width: 46,
    height: 46,
    borderRadius: 14,
    backgroundColor: COLORS.primary,
    alignItems: "center",
    justifyContent: "center",
  },
  addBtnText: {
    color: "#FFFFFF",
    fontSize: 22,
    fontWeight: "900",
    marginTop: -1,
  },

  goalHeaderTopRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
  },
  helpBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: COLORS.pinkSoft,
    borderWidth: 1,
    borderColor: "#FFC3D8",
    alignItems: "center",
    justifyContent: "center",
    marginTop: -2,
  },
  helpBtnText: {
    color: COLORS.pinkText,
    fontSize: 16,
    fontWeight: "900",
    marginTop: -1,
  },

  goalFormCard: {
    marginTop: 14,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: "#FFF6FA",
    padding: 12,
  },
  goalFormTitle: {
    fontSize: 13,
    fontWeight: "900",
    color: COLORS.pinkText,
    marginBottom: 10,
  },
  formTextArea: {
    minHeight: 74,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: COLORS.border,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 13,
    color: COLORS.text,
    backgroundColor: COLORS.white,
  },
  goalFormActions: {
    marginTop: 12,
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 10,
  },
  secondaryBtn: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 12,
    backgroundColor: COLORS.primarySoft,
  },
  secondaryBtnText: {
    color: COLORS.primary,
    fontSize: 12,
    fontWeight: "800",
  },
  primarySmallBtn: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 12,
    backgroundColor: COLORS.primary,
  },
  primarySmallBtnText: {
    color: "#FFFFFF",
    fontSize: 12,
    fontWeight: "800",
  },

  daysRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  dayCircle: {
    width: 36,
    height: 36,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.white,
    alignItems: "center",
    justifyContent: "center",
  },
  dayCircleActive: {
    borderColor: COLORS.pinkText,
    backgroundColor: COLORS.pinkText,
  },
  dayCircleText: {
    fontSize: 12,
    fontWeight: "800",
    color: COLORS.subtext,
  },
  dayCircleTextActive: {
    color: COLORS.white,
  },

  dailyHabitCard: {
    marginTop: 12,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.white,
    padding: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  dailyHabitCardCompleted: {
    backgroundColor: "#FFF6FA",
  },
  dailyHabitLeft: {
    flex: 1,
    gap: 8,
  },
  dailyHabitRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  dailyHabitTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 8,
  },
  dailyHabitTitle: {
    fontSize: 13,
    fontWeight: "900",
    color: COLORS.text,
  },

  taskCheckBtn: {
    width: 42,
    height: 42,
    borderRadius: 21,
    borderWidth: 1.5,
    borderColor: COLORS.pinkText,
    backgroundColor: COLORS.white,
    alignItems: "center",
    justifyContent: "center",
  },
  taskCheckBtnDone: {
    backgroundColor: COLORS.pinkText,
    borderColor: COLORS.pinkText,
  },
  taskCheckBtnDisabled: {
    borderColor: "#E5E7EB",
    backgroundColor: "#F9FAFB",
  },
  taskCheckBtnText: {
    fontSize: 20,
    fontWeight: "900",
    color: COLORS.pinkText,
    marginTop: -1,
  },
  taskCheckBtnTextDone: {
    color: COLORS.white,
  },
  taskCheckBtnTextDisabled: {
    color: "#D1D5DB",
  },

  dayDotsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
  },
  dayDotsRowCompact: {
    marginTop: 6,
  },
  dayDot: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.white,
    alignItems: "center",
    justifyContent: "center",
  },
  dayDotCompact: {
    width: 20,
    height: 20,
    borderRadius: 10,
  },
  dayDotActive: {
    borderColor: COLORS.pinkText,
    backgroundColor: COLORS.pinkSoft,
  },
  dayDotText: {
    fontSize: 10,
    fontWeight: "800",
    color: "#A3A0B8",
  },
  dayDotTextCompact: {
    fontSize: 9,
  },
  dayDotTextActive: {
    color: COLORS.pinkText,
  },

  smartGoalCard: {
    marginTop: 12,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.white,
    overflow: "hidden",
  },
  smartGoalCardSelected: {
    borderColor: COLORS.pinkText,
    borderWidth: 2,
  },
  smartGoalCardCompleted: {
    backgroundColor: "#FFF6FA",
  },
  smartGoalHeader: {
    minHeight: 64,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 12,
    paddingVertical: 12,
    backgroundColor: "#FFF3F8",
  },
  goalTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 8,
  },
  smartGoalTitle: {
    fontSize: 13,
    fontWeight: "900",
    color: COLORS.text,
  },
  completedTitle: {
    textDecorationLine: "line-through",
    color: COLORS.subtext,
  },
  smartGoalTime: {
    marginTop: 4,
    fontSize: 12,
    color: COLORS.subtext,
    fontWeight: "600",
  },
  completedBadge: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 999,
    backgroundColor: COLORS.pinkSoft,
    borderWidth: 1,
    borderColor: "#FFC3D8",
  },
  completedBadgeText: {
    fontSize: 10,
    fontWeight: "800",
    color: COLORS.pinkText,
  },
  goalHeaderRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  goalExpandIcon: {
    fontSize: 22,
    fontWeight: "900",
    color: COLORS.pinkText,
    width: 22,
    textAlign: "center",
  },
  smartGoalExpanded: {
    padding: 12,
    backgroundColor: COLORS.white,
  },
  smartFieldWrap: {
    marginBottom: 12,
  },
  smartFieldText: {
    marginTop: 8,
    fontSize: 12,
    lineHeight: 17,
    color: "#374151",
  },
  goalPill: {
    alignSelf: "flex-start",
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 999,
    backgroundColor: COLORS.pinkSoft,
    borderWidth: 1,
    borderColor: "#FFC3D8",
  },
  goalPillText: {
    fontSize: 12,
    fontWeight: "900",
    color: COLORS.pinkText,
  },
  goalEditRow: {
    marginTop: 4,
    alignItems: "flex-end",
  },
  goalEditBtn: {
    paddingHorizontal: 14,
    paddingVertical: 9,
    borderRadius: 12,
    backgroundColor: COLORS.primarySoft,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  goalEditBtnText: {
    fontSize: 12,
    fontWeight: "800",
    color: COLORS.primary,
  },

  linkedBadge: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 999,
    backgroundColor: COLORS.pinkSoft,
    borderWidth: 1,
    borderColor: "#FFC3D8",
  },
  linkedBadgeText: {
    fontSize: 10,
    fontWeight: "800",
    color: COLORS.pinkText,
  },
  linkedTaskPreview: {
    marginTop: 8,
  },
  linkedTaskPreviewText: {
    fontSize: 11,
    fontWeight: "700",
    color: COLORS.subtext,
    marginBottom: 6,
  },
  linkedTaskExpandedBox: {
    marginTop: 6,
    marginBottom: 12,
    borderRadius: 12,
    padding: 12,
    backgroundColor: "#FFF6FA",
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  linkedTaskExpandedTitle: {
    fontSize: 12,
    fontWeight: "900",
    color: COLORS.pinkText,
    marginBottom: 6,
  },
  linkedTaskExpandedText: {
    fontSize: 12,
    lineHeight: 17,
    color: "#374151",
    marginBottom: 8,
  },

  optionalDivider: {
    marginTop: 14,
    marginBottom: 10,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: COLORS.border,
  },
  optionalDividerText: {
    fontSize: 12,
    fontWeight: "900",
    color: COLORS.pinkText,
  },

  floatingAddBtn: {
    position: "absolute",
    right: 20,
    bottom: 24,
    width: 58,
    height: 58,
    borderRadius: 29,
    backgroundColor: COLORS.primary,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#231F5B",
    shadowOpacity: 0.16,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 5,
  },
  bottomLeftActionBtn: {
    position: "absolute",
    left: 20,
    bottom: 24,
    width: 58,
    height: 58,
    borderRadius: 29,
    backgroundColor: COLORS.pinkText,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#231F5B",
    shadowOpacity: 0.16,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 5,
  },
  floatingAddBtnText: {
    color: "#FFFFFF",
    fontSize: 30,
    fontWeight: "900",
    marginTop: -2,
  },
  bottomActionIcon: {
    color: "#FFFFFF",
    fontSize: 24,
    fontWeight: "900",
    marginTop: -1,
  },

  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(17,24,39,0.35)",
    alignItems: "center",
    justifyContent: "center",
    padding: 22,
  },
  helpModalCard: {
    width: "100%",
    maxWidth: 360,
    backgroundColor: COLORS.card,
    borderRadius: 24,
    padding: 20,
    borderWidth: 1,
    borderColor: COLORS.border,
    shadowColor: "#231F5B",
    shadowOpacity: 0.12,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
    elevation: 6,
  },
  helpIconWrap: {
    width: 64,
    height: 64,
    borderRadius: 32,
    alignSelf: "center",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: COLORS.pinkSoft,
    borderWidth: 1,
    borderColor: "#FFC3D8",
  },
  helpIconText: {
    fontSize: 28,
    fontWeight: "900",
    color: COLORS.pinkText,
    marginTop: -1,
  },
  helpModalTitle: {
    marginTop: 14,
    fontSize: 22,
    fontWeight: "900",
    color: COLORS.text,
    textAlign: "center",
  },
  helpModalSub: {
    marginTop: 6,
    fontSize: 13,
    lineHeight: 18,
    color: COLORS.subtext,
    textAlign: "center",
  },
  helpList: {
    marginTop: 18,
    gap: 10,
  },
  helpRow: {
    flexDirection: "row",
    alignItems: "flex-start",
  },
  helpEmojiCircle: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: COLORS.primarySoft,
    borderWidth: 1,
    borderColor: COLORS.border,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 10,
    marginTop: 1,
  },
  helpEmoji: {
    fontSize: 14,
  },
  helpRowText: {
    flex: 1,
    fontSize: 13,
    lineHeight: 18,
    color: COLORS.text,
    fontWeight: "600",
  },
  helpGotItBtn: {
    marginTop: 18,
    height: 48,
    borderRadius: 16,
    backgroundColor: COLORS.primary,
    alignItems: "center",
    justifyContent: "center",
  },
  helpGotItBtnText: {
    color: "#FFFFFF",
    fontSize: 15,
    fontWeight: "900",
  },
});